name: Synchronize
on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    if: github.repository == 'eidolon-ai/agent-machine'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: "Updating Dependencies"
        run: make update
      - id: git-diff
        run:
          git diff --quiet HEAD || echo "changes=true" >> $GITHUB_OUTPUT
      - id: test
        if: steps.git-diff.outputs.changes == 'true'
        uses: ./.github/start-server
      - name: Push Update
        if: steps.test.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bumping eidolon version"

  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Syncing fork with upstream
        run: |
          git config --global user.email "autosync@eidolonai.com"
          git config --global user.name "autosync"
          make sync
      - id: git-diff
        run: git diff --quiet origin/main || echo "changes=true" >> $GITHUB_OUTPUT
      - id: test
        if: steps.git-diff.outputs.changes == 'true'
        uses: ./.github/start-server
      - name: Push Sync
        if: steps.test.outcome == 'success'
        run: git push
